let data = [
    { orderId: 'CRA9938',
        status: 'delivered',
        shipTo: 'Baku',
        latLong: '53.80 33.21' },
    { orderId: 'KNQ5876',
        status: 'processing',
        shipTo: 'Yerevan',
        latLong: '50.25 31.37' },
    { orderId: 'JZH6615',
        status: 'processing',
        shipTo: 'London',
        latLong: '54.74 -1.79' },
    { orderId: 'FMU7330',
        status: 'delivered',
        shipTo: 'Brussels',
        latLong: '63.22 34.78' },
    { orderId: 'FES0369',
        status: 'delivered',
        shipTo: 'Tirana',
        latLong: '54.63 22.85' },
    { orderId: 'VJZ3314',
        status: 'delivered',
        shipTo: 'London',
        latLong: '45.10 25.23' },
    { orderId: 'XVE1808',
        status: 'shipped',
        shipTo: 'Kyiv',
        latLong: '57.24 8.09' },
    { orderId: 'VEA5015',
        status: 'processing',
        shipTo: 'Vatican City',
        latLong: '52.29 14.57' },
    { orderId: 'CKX4731',
        status: 'delivered',
        shipTo: 'Vatican City',
        latLong: '53.51 18.85' },
    { orderId: 'TEB7082',
        status: 'processing',
        shipTo: 'Vienna',
        latLong: '54.33 7.43' },
    { orderId: 'ABK9047',
        status: 'shipped',
        shipTo: 'Vienna',
        latLong: '51.92 12.10' },
    { orderId: 'JSV3073',
        status: 'processing',
        shipTo: 'Minsk',
        latLong: '48.05 3.18' },
    { orderId: 'SEL8195',
        status: 'shipped',
        shipTo: 'Kyiv',
        latLong: '60.86 18.32' },
    { orderId: 'XWP4350',
        status: 'delivered',
        shipTo: 'London',
        latLong: '57.02 26.64' },
    { orderId: 'XVA7355',
        status: 'processing',
        shipTo: 'Brussels',
        latLong: '54.08 -2.48' },
    { orderId: 'XWR0150',
        status: 'delivered',
        shipTo: 'Minsk',
        latLong: '48.81 -7.69' },
    { orderId: 'UQA0804',
        status: 'shipped',
        shipTo: 'Yerevan',
        latLong: '61.83 19.06' },
    { orderId: 'JPI3248',
        status: 'processing',
        shipTo: 'London',
        latLong: '46.85 22.03' },
    { orderId: 'LEU6331',
        status: 'shipped',
        shipTo: 'Tirana',
        latLong: '51.04 12.57' },
    { orderId: 'MMY0204',
        status: 'processing',
        shipTo: 'Kyiv',
        latLong: '58.45 -7.55' }
];

module.exports = data;